[package]
name = "fast-rl-rewards"
version = "0.1.0"
edition = "2024"

[lib]
name = "fastrlrewards"
crate-type = ["cdylib"]

[dependencies]
pyo3 = {version = "0.26.0", features = ["extension-module"]}
once_cell = "1.21.3"
regex = "1.10.6"
tempfile = "3.23.0"
wait-timeout = "0.2.1"
rayon = "1.11.0"